version: '2.3'

services:
  db:
    image: postgres
    restart: always
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_user
      POSTGRES_DB: todo

  db_check:
    build: ./db_check
    depends_on:
      - db

  adminer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
      - 8080:8081
    depends_on:
      - db
      - db_check

  backend:
    build:
      context: ..
    image: backend_django:1.0.0
    ports:
      - 8080:8080
    command: >
      bash -c "python manage.py migrate
      && python manage.py fill_db 
      &&  gunicorn todo_notes.wsgi -b 0.0.0.0:8080"
    environment:
      - TODONOTES_ON_SERVER=True
    depends_on:
      - db
      - db_check

  nginx:
    build: ./nginx
    ports:
      - 8000:8010
    depends_on:
      - backend

  frontend:
    build: ../frontend
    ports:
      - 80:80
    depends_on:
      - nginx
