version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: geekbrains
      POSTGRES_PASSWORD: geekbrains
      POSTGRES_DB: todo

  adminer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

  backend:
    container_name: 'backend_django_now'
    image: backend_django:1.0.0
    ports:
      - 8080:8080
    command: > 
      bash -c "python manage.py migrate
      && python manage.py fill_db 
      && python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - db
